import { createSlice } from '@reduxjs/toolkit'

const allCountries = [
  'Australia',
  'Austria',
  'Azerbaijan',
  'Albania',
  'Algeria',
  'Angola',
  'Andorra',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Afghanistan',
  'Bahamas',
  'Bangladesh',
  'Barbados',
  'Bahrain',
  'Belize',
  'Belarus',
  'Belgium',
  'Benin',
  'Bulgaria',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Burkina Faso',
  'Burundi',
  'Bhutan',
  'Vanuatu',
  'Vatican',
  'United Kingdom',
  'Hungary',
  'Venezuela',
  'Vietnam',
  'Gabon',
  'Haiti',
  'Guyana',
  'Gambia',
  'Ghana',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Germany',
  'Honduras',
  'Grenada',
  'Greece',
  'Georgia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Egypt',
  'Zambia',
  'Zimbabwe',
  'Israel',
  'India',
  'Indonesia',
  'Jordan',
  'Iraq',
  'Iran',
  'Ireland',
  'Iceland',
  'Spain',
  'Italy',
  'Yemen',
  'Cape Verde',
  'Kazakhstan',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Qatar',
  'Kenya',
  'Cyprus',
  'Kyrgyzstan',
  'Kiribati',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Democratic Republic of the Congo',
  'North Korea',
  'South Korea',
  'Costa Rica',
  'Ivory Coast',
  'Cuba',
  'Kuwait',
  'Laos',
  'Latvia',
  'Lesotho',
  'Liberia',
  'Lebanon',
  'Libya',
  'Lithuania',
  'Liechtenstein',
  'Luxembourg',
  'Mauritius',
  'Mauritania',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Mali',
  'Maldives',
  'Malta',
  'Morocco',
  'Marshall Islands',
  'Mexico',
  'Micronesia',
  'Mozambique',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Niger',
  'Nigeria',
  'Netherlands',
  'Nicaragua',
  'New Zealand',
  'Norway',
  'United Arab Emirates',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Poland',
  'Portugal',
  'Rwanda',
  'Romania',
  'Russia',
  'El Salvador',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'North Macedonia',
  'Seychelles',
  'Senegal',
  'Saint Vincent and the Grenadines',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Serbia',
  'Singapore',
  'Syria',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'Sudan',
  'Suriname',
  'Sierra Leone',
  'Tajikistan',
  'Thailand',
  'Tanzania',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tuvalu',
  'Tunisia',
  'Turkmenistan',
  'Turkey',
  'Uganda',
  'Uzbekistan',
  'Ukraine',
  'Uruguay',
  'Fiji',
  'Philippines',
  'Finland',
  'France',
  'Croatia',
  'Central African Republic',
  'Chad',
  'Montenegro',
  'Czech Republic',
  'Chile',
  'Switzerland',
  'Sweden',
  'Sri Lanka',
  'Ecuador',
  'Equatorial Guinea',
  'Eritrea',
  'Eswatini',
  'Estonia',
  'Ethiopia',
  'South Africa',
  'South Sudan',
  'Jamaica',
  'Japan',
]

const countrySlice = createSlice({
  name: 'countries',
  initialState: allCountries,
  reducers: {
    setCountries: (state, action) => {
      return { ...state, ...action.payload }
    },
  },
})

export const { setCountries } = countrySlice.actions

export default countrySlice.reducer
